### ISSUE TITLE
Twitter signup error: Error getting user email from external provider

### ISSUE THREAD

**Issue by magoz** [supabase-community/supabase-auth-helpers#100]
The [docs](https://supabase.com/docs/guides/auth/auth-twitter) for setting up Twitter Login are outdated.  
The 3-legged OAuth is no longer available.

I've tried what was suggested in [this discussion](https://github.com/supabase/supabase/discussions/2270).

The authentication redirection works but when I get back to my app I get the following `http://localhost:3000/?error=server_error&error_description=Error+getting+user+email+from+external+provider`

Her is my setup: 
 
<img width="695" alt="supabase1" src="https://user-images.githubusercontent.com/9190753/168739240-634a0456-949e-4d3a-984b-f253422cee01.png">

<img width="446" alt="supabase2" src="https://user-images.githubusercontent.com/9190753/168739247-13fe90a7-9999-4395-8614-4b65467c5d15.png">

Am I doing something wrong?  
What's the right way of setting up Twitter Oauth?

**Comment by thorwebdev** [comment]
This is unrelated to the helpers lib, please see here: https://github.com/supabase/gotrue/issues/214

**Comment by magoz** [comment]
Thanks @thorwebdev ! I'll look into it and the Supabase main repo and Discord.  
The Twitter user I'm testing with has an email linked.

**Comment by ervinismu** [comment]
hi @magoz i have same issue with github login, any reference for github login?

**Comment by magoz** [comment]
> hi @magoz i have same issue with github login, any reference for github login?

No, sorry, I didn't use GitHub login.

**Comment by ethanchiasson** [comment]
> Just in case somebody else has the same problem. I solved it by applying to [Elevated](https://developer.twitter.com/en/portal/products/elevated) access.

I am still getting this error even after updating to elevated status.

Also, my Twitter Developer UI looks a little different now...

<img width="665" alt="Screen Shot 2022-09-14 at 1 26 14 PM" src="https://user-images.githubusercontent.com/37730593/190233332-e67e1fea-8392-4841-8e8b-4fa8ce23c139.png">

<img width="665" alt="Screen Shot 2022-09-14 at 1 26 36 PM" src="https://user-images.githubusercontent.com/37730593/190233402-557a1c0a-232d-4d05-b047-ca80bd7a9c28.png">

I am not sure why I am still getting this error even after updating to elevated status. 

Any ideas to why this would be happening ?
