### ISSUE TITLE
What if I don't want to redirect the unauthorized user to a different page?

### ISSUE THREAD

**Issue by lumenwrites** [supabase-community/supabase-auth-helpers#105]
Hi! I'm new to Supabase and `supabase-auth-helpers`.

My goal is to fetch the Supabase user inside `getServerSideProps`, and pass it to the component I'm rendering. If the user is not authenticated, I don't want to redirect to a different page, I just want to pass a null object in place of a user.

That way I would be able to show the premium content to the authenticated users, and if the user is not authenticated, I'd be able to render a paywall into the page instead.

Is it possible to do using this library? Or am I always required to redirect the unauthorized user away from this page?

**Comment by thorwebdev** [comment]
Yes, you can pass `authRequired: false`, see https://github.com/supabase-community/supabase-auth-helpers/blob/main/examples/nextjs/pages/profile.tsx#L26

**Comment by lumenwrites** [comment]
Ah, thank you very much!

I have a similar question about the protected routes. The docs say:

> If you visit /api/protected-route without a valid session cookie, you will get a 401 response.

But what if I don't want it to automatically send the 401 response, what if I would rather do something else instead?

Also, are there are docs where I could've learned this on my own? Since I couldn't find this information in the [README](https://github.com/supabase-community/supabase-auth-helpers/blob/main/src/nextjs/README.md).
