### ISSUE TITLE
Nextjs withoutPageAuth helper

### ISSUE THREAD

**Issue by nahtnam** [supabase-community/supabase-auth-helpers#109]
Hey,

Just wondering if you think there is any value in a `withoutPageAuth` helper function which redirects the user to a different page IF they are signed in. This would essentially be the opposite of the `withPageAuth` helper and would be useful to guard pages like login/signup/marketing pages.

**Comment by thorwebdev** [comment]
You can use `withPageAuth` for that by passing `authRequired: false`: https://github.com/supabase-community/supabase-auth-helpers/blob/main/examples/nextjs/pages/profile.tsx#L26 and evaluate whether the user exists or not.

**Comment by mrmartineau** [comment]
@thorwebdev to clarify does `authRequired: false` make "the route" available for both authenticated and non-authenticated users? and it is then up to the logic in that route to determine what to do. Is that correct? Would be great to have docs on this

Also, is it possible to have a server-side redirect when `authRequired: false`? Is that when you'd use `getServerSideProps` on `withPageAuth`?

**Comment by thorwebdev** [comment]
> to clarify does authRequired: false make "the route" available for both authenticated and non-authenticated users?

Yes, correct.

> and it is then up to the logic in that route to determine what to do. Is that correct? Would be great to have docs on this

Yes, correct. And yes, docs for this are missing currently, sorry about that. 

> Also, is it possible to have a server-side redirect when authRequired: false? Is that when you'd use getServerSideProps on withPageAuth?

Yes, that's exactly it:

```js
export const getServerSideProps = withPageAuth({
  authRequired: false,
  async getServerSideProps(ctx) {
    const { user } = await getUser(ctx);
    if (user)
      return {
        redirect: {
          destination: '/account',
          permanent: false
        }
      };
    else
      return {
        props: {}
      };
  }
});
```

If you can, would be awesome if you'd create a PR to add some docs for this to the `nextjs` package README.
