### ISSUE TITLE
Element type is invalid

### ISSUE THREAD

**Issue by samtietjen** [supabase-community/supabase-auth-helpers#121]
Using this package with my project I started getting this error:
```
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```
I thought maybe it was an issue with my setup, so I tried the [supabase auth example](https://github.com/supabase/supabase/tree/master/examples/nextjs-with-supabase-auth).

Upon the initial install it worked. Updating any package at all gets me back to that same error. Even after attempting to revert the packages back to the demo version, the error remains. Any idea why this might be?

**Comment by dasearle** [comment]
Seeing the same issue here. Having used Auth without Auth-Helpers, was trying to migrate across but hit exactly this issue with the sample code.

**Comment by silentworks** [comment]
I wonder if a new version of React may have caused this, I'll test it out in the example app.

**Comment by ki7** [comment]
Hello,
It looks Like after version "@supabase/supabase-auth-helpers": "^1.0.6", the lib doesn't export the <Auth /> component anymore.
It seems that it will be handled in https://github.com/supabase-community/auth-ui.
but it is not published yet (you cannot do a `npm i @supabase/auth-ui-react`);

**Comment by silentworks** [comment]
> Hello, It looks Like after version "@supabase/supabase-auth-helpers": "^1.0.6", the lib doesn't export the `<Auth />` component anymore. It seems that it will be handled in https://github.com/supabase-community/auth-ui. but it is not published yet (you cannot do a `npm i @supabase/auth-ui-react`);

You can use the published `@supabase/ui` to get the `Auth` component for now. Btw is this the cause of the issue reported here?

**Comment by thorwebdev** [comment]
The Auth component has been removed as a dependency: https://github.com/supabase-community/supabase-auth-helpers/blob/main/CHANGELOG.md#140---2022-05-10

Please install `@supabase/ui` separately.

**Comment by ki7** [comment]
Yes I found it yesterday morning thank you.
Would you fancy a pull request updating dependencies ?
