### ISSUE TITLE
[Feature] Allow using the supabase service role key for server-side operations

### ISSUE THREAD

**Issue by devdev-dev** [supabase-community/supabase-auth-helpers#38]
It would be great if, in addition to the anon key, a service role key could be allowed to run operations without RLS.

For example, an additional env variable could be supported called SUPABASE_SERVICE_ROLE_KEY to provide a special supabaseClient for server-side operations.

**Comment by thorwebdev** [comment]
@devdev-dev if you want to use a supabase admin client with the service role key you can just create it from `supabase-js`: https://github.com/vercel/nextjs-subscription-payments/blob/main/utils/supabase-admin.ts#L7-L12

**Comment by devdev-dev** [comment]
Yes of course I already doing this, but thought it would be a great addition to this helper library to receive a session checked client with service role access.

After a second thought I can understand why it's not related to the core functionality of this package.

Nonetheless it would be a great addition for me personally 😉
