### ISSUE TITLE
Including UserProvider in my bundle added 100kbs

### ISSUE THREAD

**Issue by kaspnilsson** [supabase-community/supabase-auth-helpers#39]
These helpers are great, but seem to include a bunch of Supabase UI that I don't want.
![Screen Shot 2022-03-15 at 5 48 37 PM](https://user-images.githubusercontent.com/5749398/158495365-599759da-7808-4fb9-93ca-fbcc227ac9a6.png)

I'm only using `useUser` and `supabaseClient` from `@supabase/supabase-auth-helpers/nextjs` and `UserProvider` from `@supabase/supabase-auth-helpers/react`. Is this working as intended?

**Comment by kaspnilsson** [comment]
Looks like this is only happening due to a re-export of the auth component. Could this lib just be a peer dependency?

https://github.com/supabase-community/supabase-auth-helpers/blob/e188cb903cd532aa438729fda4269bed53b3fff5/src/react/index.tsx#L6

**Comment by thorwebdev** [comment]
Yah, we want to break out the UI stuff into it's own sub module and build a better rollup pipeline in the future.
