### ISSUE TITLE
Reduce amount of requests to Gotrue

### ISSUE THREAD

**Issue by thorwebdev** [supabase-community/supabase-auth-helpers#4]
Right now handleUser does a request to gotrue ever time. Instead we should read user data from JWT and only refetch when access_token is expired.

**Comment by GaryAustin1** [comment]
@thorwebdev 
I was looking for something else trying to bring up the nextjs version of auth-helpers, and stumbled and this "recent" change. 
 
While testing the @silentworks sveltekit version I warned him that it is pretty dangerous to just check for the token HAS EXPIRED.  I would think you need to allow reasonable time that it COULD expire during what ever you are about to do.  The token can expire a msec after you do this test and be useless at that point.
