### ISSUE TITLE
Handling (or not) userland getServerSideProps errors

### ISSUE THREAD

**Issue by a-type** [supabase-community/supabase-auth-helpers#46]
Presently the `withAuthRequired` helper wraps the invocation of the `getServerSideProps` in a try/catch block which ignores the resulting error and redirects to the login failure page. This means any error, even a runtime logic error, silently behaves the same as if the user were signed out.

Instead I think it'd be better DX to avoid catching errors from the library user's own `getServerSideProps` implementation, and let Next handle these with an error screen and server logs as usual.

It would also be helpful / good practice to log any errors caught in the helper before redirecting, so the developer knows exactly why they were treated as unauthenticated (no session? session expired? unexpected JWT error?).

I'll happily PR these changes if maintainers agree with the need.

**Comment by thorwebdev** [comment]
Yah, I think that's a good idea. PR would be appreciated 💚
