### ISSUE TITLE
"Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/app/_middleware" when deploying to vercel.com

### ISSUE THREAD

**Issue by tetaplaun** [supabase-community/supabase-auth-helpers#56]
When deploying to vercel, this warning occurs:
```
Dynamic Code Evaluation (e. g. 'eval', 'new Function') not allowed in Middleware pages/app/_middleware
```
Using the middleware as described in the README. No other middleware used.

NextJS Version 12.1.0

Possible explanation and solution:
https://github.com/vercel/next.js/issues/30674#issuecomment-955681906

Is there a  workaround?
Any advice would be appreciated!

**Comment by christopherdro** [comment]
+ 1

**Comment by arclogos132** [comment]
Same here no progress?

**Comment by davemooreuws** [comment]
I believe the fix here is to remove @supabase/supabase-js as a dependency and turn it into a peerDependency, as the issue seems to be fixed in later versions.

A work around for now is to use yarn resolutions to ensure your app is using the latest supabase-js version.

Example in package.json:

```
 "resolutions": {
    "react": "^17.0.2",
    "next": "^12.1.0",
    "@supabase/supabase-js": "^1.33.3"
  },
```

**Comment by arclogos132** [comment]
https://github.com/supabase/supabase-js/releases/tag/v1.33.3

The new release fixed this issue thanks a lot

**Comment by tetaplaun** [comment]
Works for me, too, with the latest version. Thanks for the fix!
