### ISSUE TITLE
Add additional data to user object

### ISSUE THREAD

**Issue by niklasgrewe** [supabase-community/supabase-auth-helpers#60]
Hi, thank you very much for this helper function. I am using it in my nextjs project. For my website, i need some additional data coming from a `profile` table. Before i used this package, i created a custom `UserProvider` with this:

```js
useEffect(() => {
  const getUserProfile = async () => {
    const sessionUser = supabase.auth.user()

    if (sessionUser) {
      const { data: profile } = await supabase
        .from('profile')
        .select('*')
        .eq('id', sessionUser.id)
        .single()

      setUser({
        ...sessionUser,
        ...profile,
      })

      setIsLoading(false)
    }
  }

  getUserProfile()

  supabase.auth.onAuthStateChange(() => {
    getUserProfile()
  })
}, [])
```
Can I somehow extend `supabase-auth-helpers` with my code or what is the best way to solve this? Of course I can create an additional provider, but would that be the ideal solution?

**Comment by thorwebdev** [comment]
Hey, sorry for the crazy delay, here an example of how to handle this: https://github.com/vercel/nextjs-subscription-payments/blob/main/utils/useUser.tsx#L43-L64

**Comment by roblonj** [comment]
@thorwebdev The link doesn't work.
