### ISSUE TITLE
JWT Expired when using withAuthRequired

### ISSUE THREAD

**Issue by HadiSDev** [supabase-community/supabase-auth-helpers#61]
For some reasons using withAuthRequired causes the API to respond with "JWT Expired" even though the session is refreshed.  Removing withAuthRequired solves the issue ( I checked that the user was loaded correct)

**Comment by travisanderson** [comment]
I am seeing this as well.

**Comment by thorwebdev** [comment]
Can you share more context on your setup? Are you using it in API routes? Anywhere where I can see your code? Thanks.

**Comment by wjeliot** [comment]
It seems that there was a breaking change in 1.3.0 as I don't get this error in the previous version.

**Comment by HadiSDev** [comment]
@thorwebdev Yes ofc :). It happens for me when I use it with the API endpoint. For example:

```
import {NextApiRequest, NextApiResponse} from "next";
import {getUser, supabaseServerClient, withAuthRequired} from "@supabase/supabase-auth-helpers/nextjs";
import {UserProfile} from "../../../models/user/user";


export default withAuthRequired(async function handleProfile(req: NextApiRequest, res: NextApiResponse) {
    const method = req.method
    const {user} = await getUser({req, res})
    const body = req.body as UserProfile

    if (method === "PUT") {
        const result = await supabaseServerClient({req, res})
            .from("profiles")
            .update(body).eq("user_id", user?.id)
            .single()
        res.json(result)
    }

    if (method === "GET") {
        const result = await supabaseServerClient({req, res})
            .from("profiles").select("*")
            .eq("user_id", user?.id)
            .single()

        res.json(result)
    }
})
```

If I remove the withAuthRequired  wrapper, then it works (by works I mean that the user from getuser is correctly read with the cookies)

**Comment by HadiSDev** [comment]
Just to clarify: This issue happened after I updated the package to 1.3.0

**Comment by johnbellone** [comment]
I am seeing this issue as well and opened up chat on Discord about it in #help.

**Comment by thorwebdev** [comment]
This should be fixed in https://github.com/supabase-community/supabase-auth-helpers/pull/92 can you upgrade and retry?
