### ISSUE TITLE
Update cookie anytime `getUser` is called.

### ISSUE THREAD

**Issue by krtkeyan** [supabase-community/supabase-auth-helpers#62]
### Description

I made few changes to user's metadata by `supabase.auth.api.updateUserById`. Then to refresh changes tried with `supabase.auth.refreshSession`.

This refreshes the `supabase.auth.token` in localstorage, but the user returned from `useSupaUser` still has data from cached JWT.

---
**Note**: supabase-auth-helper returns a note - `Get latest user data instead of stale one from cached JWT use getUser in serverside context`. I can able to get new user, but shouldn't the expected behaviour also refreshes the cached JWT if I called `getUser` ?

**Comment by thorwebdev** [comment]
As per the note, you will need to call `getUser` to force a refresh of the cached user cookie.

**Comment by krtkeyan** [comment]
> As per the note, you will need to call `getUser` to force a refresh of the cached user cookie.

Yes, I have tried using `getUser` in server side context via help note returned. I can able to get the update user_metadata in the current page. But when I navigate to the next page, I still get the old data. Should the cache be invalidated since I invoked `getUser` in the previous page?

**Comment by thorwebdev** [comment]
> Should the cache be invalidated since I invoked getUser in the previous page?

Yes, calling `getUser` should set the cookie, but I just checked and it only sets the cookie when the access token is expired, we need to update this to also set the cookie when the access token is still valid: https://github.com/supabase-community/supabase-auth-helpers/blob/next/src/nextjs/utils/getUser.ts#L84-L90

thanks for flagging!

**Comment by thorwebdev** [comment]
Actually, unfortunately we won't get the new access token until it is getting refreshed. Therefore You'd need to always call `getUser` when you need up validate the user_metadata. 

Alternatively, from version `1.4.0` onward you will be able to call `supabase.auth.refreshSession()` client-side to refresh the JWT & user object throughout.
