### ISSUE TITLE
onAuthStateChange does not catch auth state changes across different pages

### ISSUE THREAD

**Issue by saiabishek1** [supabase-community/supabase-auth-helpers#65]
Hi,

The issue mentioned here https://github.com/supabase/supabase/issues/2739 is what I'm running into but using `supabase-auth-helpers`

### To Reproduce

- Login via magic link
- Create an `supabaseClient.auth.onAuthStateChange()` listener in page "a" open in a tab. 
- Logout using page "b" in a different tab, and the `supabaseClient.auth.onAuthStateChange()` in page "a" is not fired.

**Comment by thorwebdev** [comment]
That's expected. We're moving away from storing things in local storage and instead are using secure HTTPS cookies. Therefore your page "a" only notices upon a future fetching of the user from the server when it sees that the cookie has been removed.
