### ISSUE TITLE
Using supabaseClient for auth.update won't update useUser() object

### ISSUE THREAD

**Issue by ferpintado** [supabase-community/supabase-auth-helpers#66]
I am trying to update a user password and metadata like so:

```javascript
import { supabaseClient } from '@supabase/supabase-auth-helpers/nextjs';
.....
.....

const { user, error } = await supabaseClient.auth.update({
    ...(new_password && { password: new_password }),
    data: {
      name,
      family_name,
      phone_number,
    },
  });
```
I can confirm that the database gets updated, however the `user` object from `useUser()` won't get updated until I log out and log back in.

As a workaround I trigger a:
```javascript
await supabaseClient.auth.refreshSession();
``` 
in order to update the user's info but I was expecting I would not need to.

Also, using supabase client from `@supabase/supabase-js` won't work as does not identify the user as logged in.

Please advise on what would be the right way to do a user update.

Cheers.

**Comment by thorwebdev** [comment]
By default the user object is cached in the cookie. To force and update you need to call `getUser()`.
