### ISSUE TITLE
UserProvider causing error when rendering on the server

### ISSUE THREAD

**Issue by billscheidel** [supabase-community/supabase-auth-helpers#68]
I added the `UserProvider` to `_app.tsx` but for some reason when rendered on the server `useRouter()` inside the provider returns null.  

```
Server Error
TypeError: Cannot read properties of null (reading 'pathname')

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
UserProvider
file:///Users/personal/Documents/offertrackr/node_modules/@supabase/supabase-auth-helpers/react/components/UserProvider.js (32:40)
```

Here is where the issue is in `UserProvider.js`:

```
    var pathname = router_1.useRouter().pathname;
```

Here is what my `_app.tsx` looks like:

```
import { supabaseClient } from '@supabase/supabase-auth-helpers/nextjs';
import { UserProvider } from '@supabase/supabase-auth-helpers/react';
import type { AppProps } from 'next/app';
import { useRouter } from 'next/router';
import React from 'react';
import '../styles/globals.css';

export default function App({ Component, pageProps }: AppProps) {
  const router = useRouter();
  console.log(useRouter);
  console.log('here', router);

  return (
    <UserProvider supabaseClient={supabaseClient}>
      <Component {...pageProps} />
    </UserProvider>
  );
}
```

When on the server, `router` in `_app.tsx` returns the `ServerRouter` correctly.  However, `useRouter()` inside of the `UserProvider` is returning null.

Is there some additional setup I need to do so that this works on both client and server?

**Comment by thorwebdev** [comment]
Thanks for reporting. https://github.com/supabase-community/supabase-auth-helpers/pull/75 will remove the router dependency in the UserProvider which should hopefully fix this.
