### ISSUE TITLE
This library adds 155kB to the "First Load JS" for every single page on my site

### ISSUE THREAD

**Issue by kristjanmar** [supabase-community/supabase-auth-helpers#69]
I tried adding this in my NextJS app and it's adding 155kB to the "First Load JS" for every single page.

I just imported UserProvider and supabaseClient from the supabase-auth-helpers library and wrapped my app in the <UserProvider>. 

Exactly as shown in the readme: https://github.com/supabase-community/supabase-auth-helpers/blob/next/src/nextjs/README.md

Here is the code: https://github.com/stockanalysisdev/stock-analysis/blob/supabase-auth-helper-test/pages/_app.tsx

First load JS -- Before: 95.6 kB
First load JS -- After: 251 kB

**Comment by thorwebdev** [comment]
The UI part will be spun out into its own package soon: https://github.com/supabase-community/supabase-auth-helpers/issues/22#issuecomment-1096445631

**Comment by cristicretu** [comment]
Same issue happened to me, terrible performance afterwards.
