### ISSUE TITLE
Make auth optional in `withAuthRequired` (`withAuth` ?)

### ISSUE THREAD

**Issue by dabarrell** [supabase-community/supabase-auth-helpers#74]
The `withAuthRequired` helper is useful for pages which should only be accessed by authenticated users, but there is a use-case for pages which are public, but could still take advantage of a `user` server-side prop when a user is authenticated.

It would be great to do something along the lines of renaming `withAuthRequired` to `withAuth`, and make `authRequired` a boolean argument – if `true`, redirect if no user is authed, if `false`, continue but set `user` to `null`.

There are clearly other options re naming the arguments etc.

**Comment by thorwebdev** [comment]
That's an interesting idea indeed, we'll discuss, thanks for suggesting!

**Comment by dijonmusters** [comment]
I think this is a fantastic idea and hit this exact problem in a side project I was working on 💯

**Comment by thorwebdev** [comment]
This is now possible via `withPageAuth`
