### ISSUE TITLE
react native support

### ISSUE THREAD

**Issue by rodbs** [supabase-community/supabase-auth-helpers#76]
I think these helpers don't work with React Native because in this function:
https://github.com/supabase-community/supabase-auth-helpers/blob/39c8a06f46a3788e463453fc743a18c98ca067ec/src/nextjs/utils/initSupabase.ts

these parameters are needed (as specified here: https://supabase.com/docs/guides/with-expo#launch )
```
export const supabase = createClient(supabaseUrl, supabaseAnonKey, {
  localStorage: AsyncStorage as any,
  autoRefreshToken: true,
  persistSession: true,
  detectSessionInUrl: false,
});
```

Any plans to support this? thx

**Comment by thorwebdev** [comment]
These helpers are for specific frameworks, e.g. the `nextjs` stuff is not meant to be used in React Native. The helpers are mainly to help with server-side things. In React Native, you can use the `supabase-js` client directly. Any reason you'd need the helpers in React Native?

**Comment by rodbs** [comment]
My idea was to try to share as much code as I can between NextJs (react-native-web ) and and React Native. 
I understand your point ... I guess for basic log in/out in React Native is enough with `supabase-js`. 
Anyway it would nice to have 'standard' React helpers/library for authentication.
