### ISSUE TITLE
Token expiration test is not accurate

### ISSUE THREAD

**Issue by GaryAustin1** [supabase-community/supabase-auth-helpers#77]
The math in at least two pieces of code yields up to 1/2 second expired token because of rounding.

utils/getUser.ts
![image](https://user-images.githubusercontent.com/54564956/164010386-dc5186a4-0b19-4596-b887-52852d9e17ee.png)
utils/getAccessToken.ts
![image](https://user-images.githubusercontent.com/54564956/164009785-89ef0aa9-8c32-4e93-a433-12fadd3266b9.png)

const timeNow = Math.round(Date.now() / 1000);
jwtUser.exp < timeNow yields:
```
jwtUser.exp       timeNow      Date.now()    
xxx1               xxx0             xxx0.499            "good" 1/2 sec to expire left  
xxx1               xxx1             xxx0.999            "good" .001 sec to expire! (not really good as no time to do anything)
xxx1               xxx1             xxx1.499            "bad" expired 1/2 sec ago but treated as not expired
xxx1               xxx2             xxx1.501             test works as it is expired for real
```

I also don't believe it is useful to have a token verified as good from cache if it can expire before even leaving the function call.  What good is a token that expires before it can even be used?

**Comment by dabarrell** [comment]
There's minimal cost in refreshing a token, so it makes sense to refresh if it expires in the next minute (?), rather than waiting for it to expire

**Comment by thorwebdev** [comment]
Yes, that's a good point. The token refresh strategy isn't ideal yet. Happy to hear ideas 🙏

**Comment by dabarrell** [comment]
@thorwebdev I've already got an open PR to set up automatic token refreshes (https://github.com/supabase-community/supabase-auth-helpers/pull/78) - I'd be happy to add this
>it makes sense to refresh if it expires in the next minute
to that PR if it works for you?

**Comment by thorwebdev** [comment]
Thanks @dabarrell, yah, I think that makes sense. I also commented on your PR, thanks for that! One note, we're currently revamping our repo setup (https://github.com/supabase-community/supabase-auth-helpers/pull/75) and then are hoping to get this in right after 👍

**Comment by dabarrell** [comment]
@thorwebdev In that case I'll wait for #75 to be merged to save a messy rebase :)
