### ISSUE TITLE
Using the name param on cookieOptions breaks withAuthRequired

### ISSUE THREAD

**Issue by bill-offertrackr** [supabase-community/supabase-auth-helpers#79]
I'm using the `nextjs` auth helpers and noticed that if you change the prefix of the cookie using the `name` param like this:

```
export default handleAuth({
  logout: { returnTo: '/' },
  cookieOptions: {
    name: 'foo',
    lifetime: 1 * 365 * 24 * 60 * 60,
  },
});
```

The cookies are created correctly, but the `withAuthRequired` helper function fails and redirects to the `redirectTo` page. 

```
export const getServerSideProps = withAuthRequired({ redirectTo: '/' });
```

 If I comment out the `withAuthRequired` handler, the page loads correctly with the user logged in and requests to the db are successful.

**Comment by silentworks** [comment]
You will need to pass the same `cookieOptions` parameter to the `withAuthRequired` otherwise the cookie name by default in `withAuthRequired` is `sb`.

The fix:
```js
export const getServerSideProps = withAuthRequired({ 
  redirectTo: '/', 
  cookieOptions: {
    name: 'foo',
    lifetime: 1 * 365 * 24 * 60 * 60,
  } 
});
```
