### ISSUE TITLE
withAuthRequired initially redirects to home page even when a user is logged in

### ISSUE THREAD

**Issue by bill-offertrackr** [supabase-community/supabase-auth-helpers#80]
I'm currently only able to get the `withAuthRequired` helper to work correctly on `nextjs` if I'm using `localhost`. If I try and access the page via  a different hosted domain (such as a Vercel staging domain) the cookies are created correctly, but `withAuthRequired` is redirecting to the logged out url the first time a protected page is accessed.  Subsequent attempts to access a protected page work just fine.

Here is the code I'm using to sign in:

```
    const { session, user, error } = await supabase.auth.signIn({
      email,
      password,
    });

    if (error) {
      setErrorMessage(error.message);
    } else {
      router.push('/protected');        
      }
    }
```

This code redirects back to the home page.  However, if I then manually try to go to `/protected` it works as expected. My user is logged in and the page loads as intended.

I'm setting the `Site URL` in the Supabase Auth Settings to match the domain that I'm trying to use.  The cookies (`sb-refresh-token` and `sb-access-token`) look like they are created correctly. The JWT token looks fine, the cookie and domain and path are set correctly.  

```
{
  "aud": "authenticated",
  "exp": 1651188262,
  "sub": "d8a90912-0757-445d-be17-437735100ca0",
  "email": "foo@example.com",
  "phone": "",
  "app_metadata": {
    "provider": "email",
    "providers": [
      "email"
    ]
  },
  "user_metadata": {},
  "role": "authenticated"
}
```

Regardless of what I've tried, the following always sends the user to the redirect url on the first page load after signing in unless I'm testing on `localhost`.  On `localhost` it loads the `/protected` URL correctly on the first attempt.

```
export const getServerSideProps = withAuthRequired({ redirectTo: '/' });
```

Is there some other config that I'm missing?

**Comment by thorwebdev** [comment]
You need to wait for the user to be set before redirecting, see an example here: https://github.com/vercel/nextjs-subscription-payments/blob/main/pages/signin.tsx#L58-L62

**Comment by mrolafsson** [comment]
Hey @thorwebdev thanks for brilliant work on this first off. I take your point entirely on redirecting only once there is a user. Maybe I'm thinking about this wrong, but I also find when I protect a nested route using `withPageAuth` and go directly to the URL it does the same redirect loop? Back to index or sign-in?
