### ISSUE TITLE
Infinity refresh for the token after login

### ISSUE THREAD

**Issue by emetelyov** [supabase-community/supabase-auth-helpers#84]
Hey! I don't know why but after login my token refreshes each second. It always requests a callback function. What am I doing wrong?

<img width="702" alt="image" src="https://user-images.githubusercontent.com/19320666/165540308-05a9954f-09a6-4ca3-9734-d062c31a9710.png">

**Comment by emetelyov** [comment]
`import { UserProvider } from "@supabase/supabase-auth-helpers/react";
import { supabaseClient } from "@supabase/supabase-auth-helpers/nextjs";
import { useRouter } from "next/router";

export default function MyApp({ Component, pageProps }) {
  const { pathname } = useRouter();
  return (
    <UserProvider supabaseClient={supabaseClient} pathname={pathname}>
      <Component {...pageProps} />
    </UserProvider>
  );
}`

**Comment by glekner** [comment]
i'm getting this aswell!, any help?

**Comment by tinezmatias** [comment]
+1

> i'm getting this aswell!, any help?

**Comment by glekner** [comment]
@emetelyov @tinezmatias 
removing this line fixes the issue, but i'm not sure at what cost.
You need to copy UserProvider to your project and edit it.

https://github.com/supabase-community/supabase-auth-helpers/blob/next/packages/react/src/components/UserProvider.tsx#L94

**Comment by emetelyov** [comment]
@glekner Ohh, thank you. 
But it's definitely not a long-term solution, need to wait for the fix.

**Comment by tinezmatias** [comment]
@emetelyov @glekner 

This works for me:
`// package.json
{
  ...
  "resolutions": {
    "@supabase/gotrue-js": "1.22.12"
  }
}`

**Comment by emetelyov** [comment]
@tinezmatias that solves the problem, thank you!

**Comment by joshgeller** [comment]
What is your JWT expiry set to in the Supabase settings?

**Comment by okezieuc** [comment]
@tinezmatias I tried your suggested solution but it does not work for me. Can you add more detail to point me in the right direction on how that works?
Also, do you think that this warning I received after running `yarn install` may have something to do with why it is not working?
```
Resolution field "@supabase/gotrue-js@1.22.12" is incompatible with requested version "@supabase/gotrue-js@^1.22.13"
```

**Comment by tinezmatias** [comment]
It's not working for me now

**Comment by silentworks** [comment]
Can someone provide a repository with an example of this happening please?

**Comment by mgm1313** [comment]
> Can someone provide a repository with an example of this happening please?

The [example in this repository](https://github.com/supabase-community/supabase-auth-helpers/tree/next/examples/nextjs) also shows this behavior. I modified it a bit to be able to run it in this codesandbox: https://codesandbox.io/s/charming-booth-nlrb9p?file=/pages/index.tsx 

![CleanShot 2022-05-04 at 09 53 32](https://user-images.githubusercontent.com/9018689/166642140-72b85a39-c5c7-4aa3-8661-5f2949b5f0ae.gif)

You can reproduce it by logging in with:
username: `info@example.com`
password: `test123`

**Comment by thorwebdev** [comment]
Folks, terribly sorry for the delay on this. We were heads down on fixing some broader token refresh issues: https://github.com/supabase/gotrue-js/releases/tag/v1.22.14

Bunch of more improvements coming tmr, but wanted to make sure get this fixed already tonight. Sorry again for the crazy delay!

**Comment by mrmartineau** [comment]
Anyone else still getting this issue or something like it after upgrading to 1.4.0?

When successfully signing in, my Network tab goes mental alternating between my sign in route and the route that we redirect to straight after sign in. I feel like this is a separate issue but wanted to check anyone else has the problem

<img width="1305" alt="image" src="https://user-images.githubusercontent.com/64883/167777067-4b76cf5a-c942-4af7-8bab-0c53559844b1.png">

FYI I am using the new `withPageAuth`

**Comment by thorwebdev** [comment]
@mrmartineau this sounds like a different issue. can you please open a new issue with repro steps / your code. Thanks.

**Comment by mrmartineau** [comment]
@thorwebdev I thought so, I created a new ticket #94
