### ISSUE TITLE
cannot find pathname of undefined

### ISSUE THREAD

**Issue by tinezmatias** [supabase-community/supabase-auth-helpers#85]
Can you please relase the fix?

PR already merged: https://github.com/supabase-community/supabase-auth-helpers/pull/75

**Comment by silentworks** [comment]
Where are you getting this issue?

**Comment by tinezmatias** [comment]
https://github.com/supabase-community/supabase-auth-helpers/issues/68

**Comment by silentworks** [comment]
Ok I got it now. We are aiming to get a release out this week but we just need to document some changes as the library name is changing along with the versioning.
