### ISSUE TITLE
Node dependencies not supported in Edge Runtime (NextJS)

### ISSUE THREAD

**Issue by chrisdunnbirch** [supabase-community/supabase-auth-helpers#90]
**Overview**

NextJS runs middleware in its Edge Runtime which does not support node dependencies and results in errors such as this:

![Screenshot 2022-05-04 at 16 35 07](https://user-images.githubusercontent.com/1064686/166838840-e97b15a3-0ef3-49ce-ac91-93c8149b2d9e.png)

**Steps to reproduce:**
1. Checkout https://github.com/chrisdunnbirch/supabase-auth-helpers-edge-runtime-test
2. `yarn install`
3. `yarn dev`
4. Visit `http://localhost:3000/should-be-protected`
    - Observe error as screenshotted above

**A single specific example**

`withMiddlewareAuthRequired` uses `jwtDecoder`: https://github.com/supabase-community/supabase-auth-helpers/blob/next/packages/nextjs/src/utils/withMiddlewareAuthRequired.ts#L60)

`jwtDecoder` from the shared package uses `Buffer`: https://github.com/supabase-community/supabase-auth-helpers/blob/next/packages/shared/utils/jwt.ts#L2.

`Buffer` is not supported in Edge Runtime which is the (non-`node`) environment in which NextJS middleware runs and only supports a handful of standard Web APIs, complete list: https://nextjs.org/docs/api-reference/edge-runtime.

**Some debugging**

I've found from _extensive_ Googling that it is possible to suppress this error by using the following code _(clarification: I do not understand what it is doing)_ in `next.config.js`:
```js
const nextConfig = {
  ...,
  webpack(config) {
    config.resolve.fallback = {
      buffer: false,
    };

    return config;
  },
}
```

This cascades through each node dependency that can't be found until the full list looks like this:
```js
const nextConfig = {
  ...,
  webpack(config) {
    config.resolve.fallback = {
      buffer: false,
      crypto: false,
      events: false,
      fs: false,
      http: false,
      https: false,
      net: false,
      os: false,
      path: false,
      querystring: false,
      stream: false,
      tty: false,
      util: false,
      zlib: false,
    };

    return config;
  },
}
```

This then causes the following error which I've yet to understand:

![Screenshot 2022-05-05 at 00 15 15](https://user-images.githubusercontent.com/1064686/166840553-2bc7836f-9307-4650-9be1-1d034004d9d6.png)

**Potential alternative solution**

I'm way out of my depth here, but at least for `Buffer` the official examples of Edge Function usage in the Vercel examples repo [use `jose` to handle JWTs which](https://github.com/vercel/examples/blob/main/edge-functions/jwt-authentication/lib/auth.ts#L25), having had a cursory glance over the internal code, does not use `Buffer`.

**Comment by 413n** [comment]
I'm getting a similar error but with the `tty` module. Probably because I have a subscription started, when I switch to a middleware-protected page it breaks.

![image](https://user-images.githubusercontent.com/16388025/167572409-463dcdef-7267-4226-9bdf-e6533a52116c.png)

In the server console I see: `Error: Cannot find module for page: /account`
To be clear, `/account` does not have an index, it's just a folder containing other pages.

_Version used: 1.3.1_

**Comment by 413n** [comment]
Hi @thorwebdev, unfortunately I'm still getting the error I sent above even with the new middleware:
```javascript
import { withMiddlewareAuth } from "@supabase/supabase-auth-helpers/nextjs/middleware";

export const middleware = withMiddlewareAuth({
  redirectTo: "/?error=notAuthenticated",
});
```

Do you have any idea? Should the `1.4.0` version have fixed this?

**Comment by chrisdunnbirch** [comment]
Indeed, this issue should not have been referenced in the release.

**Overview**

Same error as before, a node dependency is not available in the Edge Runtime:

![Screenshot 2022-05-10 at 17 50 11](https://user-images.githubusercontent.com/1064686/167681394-77d4ee3f-d1c1-41a1-a174-ba2f084026e8.png)

**Steps to reproduce:**

I've added [a branch to my example repo](https://github.com/chrisdunnbirch/supabase-auth-helpers-edge-runtime-test/pull/1/files) above to test the renamed utility.

1. Clone https://github.com/chrisdunnbirch/supabase-auth-helpers-edge-runtime-test
2. Checkout branch `test-1-4-0-release`
3. `yarn install`
4. `yarn dev`
5. Visit http://localhost:3000/should-be-protected
    - Observe error as screenshotted above

**Debugging**

The original **Some debugging** heading in this issue remains accurate.

You can suppress an error for a specific module not being found _(again: I do not understand what is happening with this `config.resolve.fallback`, I just found it in a StackOverflow thread)_ with the following:

```ts
const nextConfig = {
  ...,
  webpack(config) {
    config.resolve.fallback = {
      querystring: false,
    };

    return config;
  },
}
```

Each time you restart `yarn dev` and go back to the page it will show you another module that can't be found. You keep adding these modules to the fallback list until the full list looks like this _(Note: this is the exact same list as the original issue description)_:

```ts
const nextConfig = {
  ...
  webpack(config) {
    config.resolve.fallback = {
      buffer: false,
      crypto: false,
      events: false,
      fs: false,
      http: false,
      https: false,
      net: false,
      os: false,
      path: false,
      querystring: false,
      stream: false,
      tty: false,
      util: false,
      zlib: false,
    };

    return config;
  },
}
```

Once you've added each module that couldn't be found in the Edge Runtime environment, you are presented with the following error:

![Screenshot 2022-05-10 at 17 58 01](https://user-images.githubusercontent.com/1064686/167683089-86e806db-6a43-40f3-ad1b-f534f81dd821.png)

**Comment by ZicklePop** [comment]
I think I'm in this same situation.

```
./node_modules/debug/src/node.js
Module not found: Can't resolve 'tty' in '/node_modules/debug/src'

Import trace for requested module:
./node_modules/debug/src/index.js
./node_modules/websocket/lib/WebSocketServer.js
./node_modules/websocket/lib/websocket.js
./node_modules/websocket/index.js
./node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
./node_modules/@supabase/realtime-js/dist/module/index.js
./node_modules/@supabase/supabase-js/dist/module/index.js
./node_modules/@supabase/supabase-auth-helpers/nextjs/middleware/withMiddlewareAuth.js
./node_modules/@supabase/supabase-auth-helpers/nextjs/middleware/index.js
./pages/feed/_middleware.js

./node_modules/debug/src/node.js
Module not found: Can't resolve 'util' in '/node_modules/debug/src'

Import trace for requested module:
./node_modules/debug/src/index.js
./node_modules/websocket/lib/WebSocketServer.js
./node_modules/websocket/lib/websocket.js
./node_modules/websocket/index.js
./node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
./node_modules/@supabase/realtime-js/dist/module/index.js
./node_modules/@supabase/supabase-js/dist/module/index.js
./node_modules/@supabase/supabase-auth-helpers/nextjs/middleware/withMiddlewareAuth.js
./node_modules/@supabase/supabase-auth-helpers/nextjs/middleware/index.js
./pages/feed/_middleware.js

./node_modules/debug/src/node.js
Module not found: Can't resolve 'fs' in '/node_modules/debug/src'

Import trace for requested module:
./node_modules/debug/src/index.js
./node_modules/websocket/lib/WebSocketServer.js
./node_modules/websocket/lib/websocket.js
./node_modules/websocket/index.js
./node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
./node_modules/@supabase/realtime-js/dist/module/index.js
./node_modules/@supabase/supabase-js/dist/module/index.js
./node_modules/@supabase/supabase-auth-helpers/nextjs/middleware/withMiddlewareAuth.js
./node_modules/@supabase/supabase-auth-helpers/nextjs/middleware/index.js
./pages/feed/_middleware.js

./node_modules/debug/src/node.js
Module not found: Can't resolve 'net' in '/node_modules/debug/src'

Import trace for requested module:
./node_modules/debug/src/index.js
./node_modules/websocket/lib/WebSocketServer.js
./node_modules/websocket/lib/websocket.js
./node_modules/websocket/index.js
./node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
./node_modules/@supabase/realtime-js/dist/module/index.js
./node_modules/@supabase/supabase-js/dist/module/index.js
./node_modules/@supabase/supabase-auth-helpers/nextjs/middleware/withMiddlewareAuth.js
./node_modules/@supabase/supabase-auth-helpers/nextjs/middleware/index.js
./pages/feed/_middleware.js

./node_modules/next/dist/compiled/native-url/index.js
Module not found: Can't resolve 'querystring' in '/node_modules/next/dist/compiled/native-url'

Import trace for requested module:
./node_modules/websocket/lib/WebSocketClient.js
./node_modules/websocket/lib/websocket.js
./node_modules/websocket/index.js
./node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
./node_modules/@supabase/realtime-js/dist/module/index.js
./node_modules/@supabase/supabase-js/dist/module/index.js
./node_modules/@supabase/supabase-auth-helpers/nextjs/middleware/withMiddlewareAuth.js
./node_modules/@supabase/supabase-auth-helpers/nextjs/middleware/index.js
./pages/feed/_middleware.js
```

**Comment by chrisdunnbirch** [comment]
Thank you for this fix! 🙏

**Comment by ChronSyn** [comment]
It seems that this issue is still happening.

I've only very recently tried to implement these auth helpers into a project, and I am so confused by what actually should work right now, what the correct combination of packages is.

```
../../node_modules/node-gyp-build/index.js:1:0
Module not found: Can't resolve 'fs'

Import trace for requested module:
../../node_modules/bufferutil/index.js
../../node_modules/websocket/lib/WebSocketFrame.js
../../node_modules/websocket/lib/websocket.js
../../node_modules/websocket/index.js
../../node_modules/@supabase/realtime-js/dist/module/RealtimeClient.js
../../node_modules/@supabase/realtime-js/dist/module/index.js
../../node_modules/@supabase/supabase-js/dist/module/index.js
../../node_modules/@supabase/auth-helpers-shared/dist/index.mjs
../../node_modules/@supabase/auth-helpers-nextjs/dist/index.js
./middleware.ts

https://nextjs.org/docs/messages/module-not-found

You're using a Node.js module (fs) which is not supported in the Edge Runtime.
Learn more: https://nextjs.org/docs/api-reference/edge-runtime
```

**Package.json** - versions below are the latest at the time of writing
```
"@supabase/auth-helpers-nextjs": "^0.4.1",
"@supabase/auth-helpers-react": "^0.3.0",
"@supabase/supabase-js": "^2.0.4",
"next": "12.2.0",
```

**Node**: 16.15.0

**middleware.ts**
```
import { withMiddlewareAuth } from '@supabase/auth-helpers-nextjs'

export const middleware = withMiddlewareAuth({ redirectTo: '/login' })

export const config = {
  matcher: ['/portal/:path*'],
}
```

To clarify, the error appears only if the contents of `middleware.ts` are as above. I can use a next-native middleware (e.g. below) and experience no issues:

```
export function middleware(request: NextRequest) {
  const url = request.nextUrl.clone()
  if (url.pathname === '/portal') {
    url.pathname = '/login'
    return NextResponse.redirect(url)
  }
}
```

Additionally, the `withPageAuth` method used for protecting individual pages appears to work correctly without throwing errors.
