### ISSUE TITLE
NextJS api returns "Atob is not found" when deployed on Vercel

### ISSUE THREAD

**Issue by dukesx** [supabase-community/supabase-auth-helpers#97]
## What i see

I recently switched from supabase-js to this auth helpers library hoping it will ease things a bit. I was previously using v1.31 when i migrated to 1.4.1 and now it seems that _middleware sometimes either detects the cookie or does not. 

Regardless, it still redirects me to homepage (default if no session) even if COOKIE exists in every network request (already logged in) and also the useUser hook returns me user as null. 

## The baseline
Provided that supabaseClient from auth helpers DOES set server sided cookie, i should not have faulty redirects or a null user (if i log in).

## Where ?
I am seeing this behavior on Vercel deployments only. Note that on localhost this seems to work fine for some reason. I have tried invalidate and revalidate cache to avoid caching errors but does not seem to be the issue.

**Comment by dukesx** [comment]
I think i found the problem, the issue is arising from "atob" not found when supabase sends request to api. It seems that edge functions donot support Node environment hence atob is not available.

**Comment by dukesx** [comment]
Duplicate of #93

**Comment by dukesx** [comment]
Response from api :

```json
{  
"user":null,
"accessToken":null,
"error":"atob is not defined"
   }
```

**Comment by ferpintado** [comment]
I am experiencing the same problem after upgrading to 1.4.x

**Comment by dukesx** [comment]
@ferpintado but luckily Next js has an ace up their sleeve. If Edge middleware makes it easy and simple to get, set and delete  cookies using NextResponse, maybe node js requirement will end. I have seen this PR and its merged a few days ago. Hopefully supabase team can leverage this new NextResponse api to fix this issue once and for all.

**Comment by thorwebdev** [comment]
The nextjs docs call out `atob` as supported: https://nextjs.org/docs/api-reference/edge-runtime#base64

**Comment by thorwebdev** [comment]
@dukesx setting the cookies isn't the problem, it's decoding the JWT. I was hoping to avoid introducing a dependency for this, but maybe we will need to move to using Jose.

**Comment by dukesx** [comment]
@thorwebdev i can confirm, atob issue goes away with switching to  node 16 in Vercel but you will need to include this nifty tip in the read me of auth helpers, for those experiencing cookie issues on Vercel. This may help in avoiding the dependency. There is however another issue related to next js and redirects after logging in.
