### ISSUE TITLE
Problem with Gitlab and Github provider

### ISSUE THREAD

**Issue by gperdomor** [supabase-community/supabase-auth-helpers#98]
For some reason when i tried to login with github or gitlab provider, the access token is not decoed properly and got invalid character error, the problem is in jwt decoder in atob call...

With google provider works without problem...

If the first login is with google (the user is created in supabase table with the google provider), then the github or gitlab login works too

<img width="279" alt="Screen Shot 2022-05-14 at 7 21 36 PM" src="https://user-images.githubusercontent.com/371939/168451082-ce31a4eb-8bfe-4ed3-a94c-925ad1a2f87b.png">

**Comment by thorwebdev** [comment]
Can you provide a JWT where you are experiencing this? For me GitHub is working fine, but I assume it might be some character in the GitHub name etc, not sure.

**Comment by ilyabo** [comment]
I experience the same error when trying to log in with GitHub:

![image](https://user-images.githubusercontent.com/351828/169045685-f0e91272-166a-4f71-aa73-d31e6750d050.png)

**Comment by gperdomor** [comment]
@thorwebdev for me this is the token eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjUyOTMwMTYzLCJzdWIiOiI4OWMzNDFjMS1hYjdkLTQ2ZGQtYjI4Ni1lYzI3ZjZjZTg1ZmMiLCJlbWFpbCI6ImdwZXJkb21vckBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImdpdGh1YiIsInByb3ZpZGVycyI6WyJnaXRodWIiXX0sInVzZXJfbWV0YWRhdGEiOnsiYXZhdGFyX3VybCI6Imh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS8zNzE5Mzk_dj00IiwiZW1haWwiOiJncGVyZG9tb3JAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZ1bGxfbmFtZSI6Ikd1c3Rhdm8gUGVyZG9tbyIsImlzcyI6Imh0dHBzOi8vYXBpLmdpdGh1Yi5jb20iLCJuYW1lIjoiR3VzdGF2byBQZXJkb21vIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZ3BlcmRvbW9yIiwicHJvdmlkZXJfaWQiOiIzNzE5MzkiLCJzdWIiOiIzNzE5MzkiLCJ1c2VyX25hbWUiOiJncGVyZG9tb3IifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQifQ.322ljhqoYDIb0vEkYe8_Av_Udp_JiPXEapkoROIj6Z0
