### ISSUE TITLE
Invalid character error when signing up with Facebook

### ISSUE THREAD

**Issue by magoz** [supabase-community/supabase-auth-helpers#99]
When I try to signup with Facebook, the flow seems to work properly on the Facebook side and I get redirected to my app.
But when I get redirected to my app  I get the error `Invalid character`. 

In the Auth dashboard of Supabase, I can see that the sign-up was logged and successful.

This is what `/api/auth/user` gives me after the signup.

```
{
  "user": null,
  "accessToken": null,
  "error": "Invalid character"
}
```

Google sign-in works as expected. And Magic Link works too.

I'm using the latest versions of the Supabase libraries:
- "@supabase/supabase-auth-helpers": "^1.4.1"
- "@supabase/supabase-js": "^1.35.3"
- "@supabase/ui": "^0.36.5"

And I'm using the latest version of nextjs (12.1.6).

Might it be related to #98?
I don't have Github or Gitlab providers, but I can confirm that Google auth works as expected.

Any ideas?

**Comment by gperdomor** [comment]
Yes it's the same issue from #98

**Comment by thorwebdev** [comment]
Can you provide a JWT where you are experiencing this? For me GitHub is working fine, but I assume it might be some character in the GitHub name etc, not sure.

**Comment by magoz** [comment]
This is what I get back from Facebook.

```
http://localhost:3000/#access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjUyNzY3MTEyLCJzdWIiOiI3Y2NkOGM1Zi05ODRlLTQ5YTAtYjU0MC0wOTVlOGY1MTUwZDMiLCJlbWFpbCI6Im1hZ296NDdAZ21haWwuY29tIiwicGhvbmUiOiIiLCJhcHBfbWV0YWRhdGEiOnsicHJvdmlkZXIiOiJmYWNlYm9vayIsInByb3ZpZGVycyI6WyJmYWNlYm9vayJdfSwidXNlcl9tZXRhZGF0YSI6eyJhdmF0YXJfdXJsIjoiaHR0cHM6Ly9wbGF0Zm9ybS1sb29rYXNpZGUuZmJzYnguY29tL3BsYXRmb3JtL3Byb2ZpbGVwaWMvP2FzaWQ9NDk3NDIzODQxNTk2NDk0Nlx1MDAyNmhlaWdodD01MFx1MDAyNndpZHRoPTUwXHUwMDI2ZXh0PTE2NTUzNTU1MTJcdTAwMjZoYXNoPUFlUXFNcUZvQ3NwSklTS3BPSFkiLCJlbWFpbCI6Im1hZ296NDdAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZ1bGxfbmFtZSI6Ik1hZ296IE3DoWdveiIsImlzcyI6Imh0dHBzOi8vZ3JhcGguZmFjZWJvb2suY29tL21lP2ZpZWxkcz1lbWFpbCxmaXJzdF9uYW1lLGxhc3RfbmFtZSxuYW1lLHBpY3R1cmUiLCJuYW1lIjoiTWFnb3ogTcOhZ296Iiwibmlja25hbWUiOiJNYWdveiBNw6Fnb3oiLCJwaWN0dXJlIjoiaHR0cHM6Ly9wbGF0Zm9ybS1sb29rYXNpZGUuZmJzYnguY29tL3BsYXRmb3JtL3Byb2ZpbGVwaWMvP2FzaWQ9NDk3NDIzODQxNTk2NDk0Nlx1MDAyNmhlaWdodD01MFx1MDAyNndpZHRoPTUwXHUwMDI2ZXh0PTE2NTUzNTU1MTJcdTAwMjZoYXNoPUFlUXFNcUZvQ3NwSklTS3BPSFkiLCJwcm92aWRlcl9pZCI6IjQ5NzQyMzg0MTU5NjQ5NDYiLCJzbHVnIjoiTWFnb3ogTcOhZ296Iiwic3ViIjoiNDk3NDIzODQxNTk2NDk0NiJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCJ9.WTUmxQrW5-T4QrIPrqc9fRwIyX5ET_Sf3R2zMsjiF7g&expires_in=3600&provider_token=EABLEuIn2GjYBAEm41tnRqnbHdF8O4qGGdWgXxvw2WGa39pGejwl65fthPFtBdZApMFUJAH60HMkC8yIgFLRhvXy2hPal3tZCCdeMgZASEhOgVadZA8zGbOtWUtNKnYvuabeZCEQRSkCHDW941VXvmiVZBmsZBYIUDCWEJKjHlp0WcjQjCZB0RrxN37ZBtBTJ4hyU5PuzYA4V0lG3NOOE2DlTJZAzgQ7qc4aAB4zGxrCpSfaAZDZD&refresh_token=NQ78oP9R6NxIi_lP1RlqXg&token_type=bearer
```

I don't know how but now the signup with Facebook works, and I haven't changed anything on my code.  
I guess this is the same strange behaviour that @gperdomor  is describing:

> If the first login is with google (the user is created in supabase table with the google provider), then the github or gitlab login works too

**Comment by gperdomor** [comment]
@thorwebdev for me this is the token `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNjUyOTMwMTYzLCJzdWIiOiI4OWMzNDFjMS1hYjdkLTQ2ZGQtYjI4Ni1lYzI3ZjZjZTg1ZmMiLCJlbWFpbCI6ImdwZXJkb21vckBnbWFpbC5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImdpdGh1YiIsInByb3ZpZGVycyI6WyJnaXRodWIiXX0sInVzZXJfbWV0YWRhdGEiOnsiYXZhdGFyX3VybCI6Imh0dHBzOi8vYXZhdGFycy5naXRodWJ1c2VyY29udGVudC5jb20vdS8zNzE5Mzk_dj00IiwiZW1haWwiOiJncGVyZG9tb3JAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImZ1bGxfbmFtZSI6Ikd1c3Rhdm8gUGVyZG9tbyIsImlzcyI6Imh0dHBzOi8vYXBpLmdpdGh1Yi5jb20iLCJuYW1lIjoiR3VzdGF2byBQZXJkb21vIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZ3BlcmRvbW9yIiwicHJvdmlkZXJfaWQiOiIzNzE5MzkiLCJzdWIiOiIzNzE5MzkiLCJ1c2VyX25hbWUiOiJncGVyZG9tb3IifSwicm9sZSI6ImF1dGhlbnRpY2F0ZWQifQ.322ljhqoYDIb0vEkYe8_Av_Udp_JiPXEapkoROIj6Z0`

**Comment by masa5714** [comment]
The same error occurred on Twitter.

Problems occur in the following cases

- Case 1 : SignIn -> Name contains @ or _.
- Case 2 : SignUp -> Profile text contains @ or _.

```js
// Success ( https://supabase.com/docs/guides/auth/auth-twitter )
import { supabase } from "../src/utils/supabaseClient";

~ ~

const { user, error } = await supabase.auth.signIn({
  provider: "twitter",
});
```

```js
// Failed ( Invalid character )
import { supabaseClient } from "@supabase/supabase-auth-helpers/nextjs"

~ ~

const { user, error } = await supabaseClient.auth.signIn({
  provider: "twitter",
});
```

Based on the above results, I believe the problem is specific to supabase-auth-helpers.
